global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'azure-servicebus-exporter'
    scrape_interval: 60s  # Should match azure.servicebus.metrics.scrape-interval
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['azure-servicebus-exporter:8080']