apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-servicebus-metric-exporter.fullname" . }}-secret
  labels:
    {{- include "azure-servicebus-metric-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  connection-string: {{ .Values.azureServiceBus.connectionString | b64enc }}